language: python
python:
  - "3.4"

install:
  - "pip install -e ."
  - "pip install pyflakes"
  - "pip install pep8"

script:
  - "python setup.py test"
  - "pep8 mnemonicode setup.py"
  - "pyflakes mnemonicode setup.py"

deploy:
  provider: pypi
  user: "bwhmather-travis"
  password:
    secure: "obcTLRBOVAnEGyMpOnv+/AZriOPha8WPl6ftgZmJNS++Jo/9N37zIH1xODjstWj+784NzPIoUgKQYfviFCAcB62wxBQRpd3Rqu7R6XhM5oCh/pkKqqRHXyNeB+8lhQ3WsU+2Tp/hFgSPM6OpBIS5sc1UvwqCLXxDDIBksX5e12M="
  on:
    branch: "master"
